### ISSUE TITLE
RE "Instead of installing the gem manually, consider using Bundler."

### ISSUE THREAD

**Issue by HankBrown** [lolmaus/breakpoint-slicer#14]
New to ruby and Bundler. Created gemfile and got breakpoint, but do not know how/what to do for slicer. Please forgive me and delete if this is the wrong place to ask. But I hope you'll consider adding details to that instruction. Thank you.
```
# A sample Gemfile
source "https://rubygems.org"

# gem "rails"
gem "breakpoint", "~>2.4.0"

## dsm 6 jan 15 failed to guess how to do this
## https://github.com/lolmaus/breakpoint-slicer
## gem "slicer", "1.36"
```

Current link that says "consider Bundler" actually goes to 
https://github.com/at-import/Singularity o
I think you want it to go to
http://bundler.io/v1.7/git.html

At that page I got this idea:
```
gem 'slicer', "1.36", :git => 'https://github.com/lolmaus/breakpoint-slicer'
```
But am still at a loss to get started
```
$ Bundler install 
Updating https://github.com/lolmaus/breakpoint-slicer
There was a LoadError while loading breakpoint-slicer.gemspec: 
cannot load such file -- compass from
  /Users/me/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/breakpoint-slicer-f057dcb5ae52/breakpoint-slicer.gemspec:2:in `<main>'

Does it try to require a relative path? That's been removed in Ruby 1.9.
```

It wants compass? Yet I have compass and was generating sass stylesheets.

**Comment by HankBrown** [comment]
Actually the link to Bundler goes to https://github.com/at-import/Singularity on your README.

**Comment by lolmaus** [comment]
Yeah, URL to Bundler was wrong. I fixed it, thank you for pointing it out.

Bundler usage is out of scope of this project's readme. You should google for a basic howto. I've googled for "bundler compass" and immediately found a nice guide: http://atendesigngroup.com/blog/managing-compass-extensions-bundler

Below i'll outline the steps. I haven't read that guide but i'm sure it boils down to the same scenario:

1. Create a proper `Gemfile` in your project's root.
2. In that file, list all your Ruby dependencies, including Compass.
3. Run `bundle install` to install the dependencies. This will create a `Gemfile.lock`.
4. Make sure to check both `Gemfile` and `Gemfile.lock` into version control.
4. From now on, prefix command line calls to Ruby programs with `bundle exec`, for example:

        bundle exec compass compile

I'm closing this ticket as it's not an issue with Breakpoint Slicer. I'm still glad to answer your questions, just write a follow-up comment.

**Comment by HankBrown** [comment]
Thank you for a prompt response. Your suggestion to checkin Gemfile was valuable news.
As for the rest, yes, did that the first time, the error persists. 
It was worth asking here first before I begin the search for a solution.....
cheers

**Comment by lolmaus** [comment]
The error kinda looks like a problem on my part. Tomorrow i'll try to do the steps myself and report back.

Meanwhile, can you share a github link to your project, so that i can check it?

**Comment by HankBrown** [comment]
Oh! I was not expecting that! 

Um. No, the best I can do is send a zip. I was going to attach it but
noticed your address. Prefer this not be public in any way yet. 

I'm just getting started and the project is an early alpha state. It did
compile without bundle. I wanted to add breakpoint and slicer. 

Perhaps my structure is wrong/unexpected. I'm not clear on it all myself
yet. 

Confirm this email is private and I will send zip. 

I notice my bash_profile has changed. I cannot help but wonder... 

## dsm 12 dec 14
## This path to sencha Cmd includes ruby, compass sass etc
## I do not know what versions or whether it was inteded to be shared
## Hopefully it lives in it's own world.
export PATH=/Users/brownhanky/bin/Sencha/Cmd/5.1.0.26:$PATH 

# dsm when? sometime after above
# Dont know who how or why
# Ruby Version Manager ? 
#[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" #
Load RVM into a shell session *as a function* 

## dsm 7 jan 15 : Now what? Who put this here and why? Bundle?
eval "$(rbenv init -)" 

export PATH=/usr/local/bin:$PATH 

*** 

If your software made an entry, consider also entering a comment? 

I am grateful for your time, thank you. 

On 2015-01-07 13:36, Andrey Mikhaylov (lolmaus) wrote: 

> The error kinda looks like a problem on my part. Tomorrow i'll try to do the steps myself and report back. 
> 
> Meanwhile, can you share a github link to your project, so that i can check it? 
> 
> --
> Reply to this email directly or view it on GitHub [1].

 

Links:
------
[1]
https://github.com/lolmaus/breakpoint-slicer/issues/14#issuecomment-69096408

**Comment by lolmaus** [comment]
I've tried it and it worked for me fine.

To help me resolve your issue, please share the following files via https://gist.github.com :

* Gemfile
* Gemfile.lock
* config.rb
* the sass/scss file where you import dependencies

**Comment by HankBrown** [comment]
Thank you so much for your time. 

This turns out to be a path conflict. 

I develop with sencha Cmd, and they use their own versions of
ruby,sass,compass etc. 

When I took their path out of my environment, installation proceeded as
expected. 

However, I used gem install over bundler. 

Not sure exactly, but enough to say it is my problem. 

Sorry to consume your time. 

On 2015-01-10 15:23, Andrey Mikhaylov (lolmaus) wrote: 

> I've tried it and it worked for me fine. 
> 
> To help me resolve your issue, please share the following files via https://gist.github.com [1] : 
> 
> * Gemfile
> * Gemfile.lock
> * config.rb
> * the sass/scss file where you import dependencies
> 
> --
> Reply to this email directly or view it on GitHub [2].

 

Links:
------
[1] https://gist.github.com
[2]
https://github.com/lolmaus/breakpoint-slicer/issues/14#issuecomment-69476422
